# Generated by Django 3.2.5 on 2021-07-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodapp', '0002_auto_20210725_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prof_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default_wijiaj', upload_to='profile_photos/'),
        ),
    ]
